### ISSUE TITLE
verifica1.sql

### ISSUE THREAD

**Issue by RuggieroB** [RuggieroB/database#1]
@FabioZTessitore Buongiorno,
Ho caricato il database "verifica1". SQLite3 mi fa le bizze e non riesco a capire perchè, ne a terminare la verifica del database, poichè non legge delle righe, da errori a righe inesistenti, accetta parametri uguali in modi diversi e non riconosce le tabelle.
Fiducioso in Lei, Le auguro una piacevole giornata ed una piacevole settimana
S.E. Co. ERBB

**Comment by FabioZTessitore** [comment]
ho trovato tutta una serie di piccoli errori. Per il momento ho commentato molta parte del codice così da aggiustare un po' alla volta.

Il primo passo è aggiustare le date degli Attori. Sqlite3 non ammette solo la data, ma almeno YYYY-MM-DD
